# 
# MSI DDSS 2021/2022 - Assignment 2
# The code and resources available in this repository are to be used in the scope of the DDSS course.
#
# Authors: Nuno Antunes <nmsa@dei.uc.pt>, Jo√£o Antunes <jcfa@dei.uc.pt>
#
version: '3'

services:
  db:
    build: ./postgresql
    container_name: db
    expose:
      - "5432"
    ports:
      - "5432:5432"
  web:
    build: ./java
    container_name: web
    expose:
      - "4567"
    ports:
      - "8080:4567"
    depends_on:
      - db